//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Barcode_Master
    {
        public string Barcode_Number { get; set; }
        public string Billing_Number { get; set; }
        public string Billing_Token_number { get; set; }
        public System.DateTime Date { get; set; }
        public string Marchent_Token_number { get; set; }
        public byte[] Image { get; set; }

        public virtual Billing_Master Billing_Master { get; set; }
    }
}

