
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [Display(Name = "Token")]
        public string Token_number { get; set; }
        [Display(Name = "Customer name")]
        public string Customer_Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        [Display(Name = "Phone number")]
        public string Phone_number { get; set; }
        [Display(Name = "Alternate phone number")]
        public string Alternate_phone_number { get; set; }
        public Nullable<int> State { get; set; }
        [Display(Name = "State name")]
        public string State_Name { get; set; }
        public string Address { get; set; }
        [Display(Name = "Second address")]
        public string Second_Address { get; set; }
        [Display(Name = "pan number")]
        public string Pan_number { get; set; }
        [Display(Name = "Credit Card number")]
        public string Credit_Card_number { get; set; }
        [Display(Name = "Credit limit")]
        public double Credit_limit { get; set; }
        [Display(Name = "Approve")]
        public bool IsActive { get; set; }

        public string Marchent_Token_number { get; set; }
        [Display(Name = "Applied date")]
        public System.DateTime Applied_date { get; set; }
        [Display(Name = "Approve date")]
        public System.DateTime Approve_date { get; set; }
        [Display(Name = "New customer")]
        public bool New_customer { get; set; }

        public virtual State State1 { get; set; }
    }
}


