
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Customer_shipping_address
    {
        public string Customer_token_number { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string Address_Line1 { get; set; }
        public string Address_Line2 { get; set; }
        public string Town_City { get; set; }
        public string State { get; set; }
        public string Pin_code { get; set; }
        public string Phone_number { get; set; }
        public string Email { get; set; }
        public bool IsUser { get; set; }
    }
}

