//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Dealer
    {
        [Display(Name = "Token")]
        public string Token_number { get; set; }
        [Display(Name = "Dealer code")]
        public string Dealer_code { get; set; }

        public string Name { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        [Display(Name = "Ph number")]
        public string Phone_number { get; set; }
        public Nullable<int> State { get; set; }
        [Display(Name = "State name")]
        public string State_Name { get; set; }
        [Display(Name = "Approve")]
        public bool Isactive { get; set; }
        public string Marchent_Token_number { get; set; }

        public virtual State State1 { get; set; }
    }
}

