//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EasyBillingEntities : DbContext
    {
        public EasyBillingEntities()
            : base("name=EasyBillingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Barcode_Master> Barcode_Masters { get; set; }
        public virtual DbSet<Billing_Detail> Billing_Details { get; set; }
        public virtual DbSet<Billing_Master> Billing_Masters { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Customer_shipping_address> Customer_shipping_addresses { get; set; }
        public virtual DbSet<Dealer> Dealers { get; set; }
        public virtual DbSet<Marchent_Account> Marchent_Accounts { get; set; }
        public virtual DbSet<Marchent_account_payment_detail> Marchent_account_payment_details { get; set; }
        public virtual DbSet<Placed_Order> Placed_Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Products_For_Sale> Products_For_Sales { get; set; }
        public virtual DbSet<Purchase_detail> Purchase_details { get; set; }
        public virtual DbSet<Purchase_Master> Purchase_Masters { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<Stockout> Stockouts { get; set; }
        public virtual DbSet<Tax_Group> Tax_Groups { get; set; }
        public virtual DbSet<Transaction_amount_detail> Transaction_amount_details { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Temp_placedorder> Temp_placedorder { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<Proprietor> Proprietors { get; set; }
        public virtual DbSet<Tyre_size> Tyre_sizes { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<Other_Product> Other_Products { get; set; }
        public virtual DbSet<Item_Tube> Item_Tubes { get; set; }
        public virtual DbSet<Item_Tyre> Item_Tyres { get; set; }
        public virtual DbSet<Purchase_Invoice> Purchase_Invoices { get; set; }
    }
}
