
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [Display(Name = "Token")]
        public string Token_number { get; set; }
        [Display(Name = "Employee id")]
        public string Employee_Id { get; set; }
        [Display(Name = "Employee name")]
        public string Employee_name { get; set; }
        public string Designation { get; set; }
        [Display(Name = "Joining date")]
        public System.DateTime Joining_date { get; set; }
        [Display(Name = "Contact number")]
        public string Contact_number { get; set; }
        [Display(Name = "Email id")]
        public string Email_id { get; set; }
        public decimal Salary { get; set; }
        [Display(Name = "Leaving date")]
        public System.DateTime Leaving_date { get; set; }
        [Display(Name = "Login required")]
        public bool login_required { get; set; }

    }
}


