//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Item_Tube
    {
        public string Token_number { get; set; }
        public string Item_Id { get; set; }
        public string Tube_size { get; set; }
        public string Company_name { get; set; }
        public string Vehicle_type { get; set; }
        public string Description { get; set; }
    }
}

