//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Manager
    {
        [Display(Name = "Token")]
        public string Token_number { get; set; }
        [Display(Name = "Manager name")]
        public string Manager_name { get; set; }
        [Display(Name = "Email id")]
        public string Email_Id { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        [Display(Name = "State code")]
        public Nullable<int> State_Code { get; set; }
        [Display(Name = "Pan number")]
        public string Pan_Number { get; set; }
        [Display(Name = "Approve")]
        public bool IsActive { get; set; }
        [Display(Name = "Password")]
        public string Verification_code { get; set; }
        [Display(Name = "State name")]
        public string State_Name { get; set; }
    }
}

