//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Marchent_account_payment_detail
    {
        public string GLCODE { get; set; }
        public string Account_name { get; set; }
        public string Card_number { get; set; }
        public string Marchent_token { get; set; }
    }
}

