
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Other_Product
    {
        [Display(Name = "Token number")]
        public string Token_number { get; set; }
        [Display(Name = "Product name")]
        public string Product_name { get; set; }
        [Display(Name = "Product type")]
        public string Product_type { get; set; }

        public string Description { get; set; }
    }
}

