//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Products_For_Sale
    {
        [Display(Name = "Token")]
        public string Token_Number { get; set; }
        [Display(Name = "Company Token")]
        public string Product_Token { get; set; }
        [Display(Name = "Company name")]
        public string Product_name { get; set; }
        public int Pieces { get; set; }
        [Display(Name = "Amount including tax")]
        public decimal Amout_after_tax { get; set; }
        public decimal Total { get; set; }
        [Display(Name = "Tyre size")]
        public string Tyre_Size { get; set; }
        [Display(Name = "Supplier token")]
        public string Supplier_token { get; set; }
        [Display(Name = "Supplier name")]
        public string Supplier_name { get; set; }
        public System.DateTime Date { get; set; }
        [Display(Name = "Purchase price")]
        public decimal Purchase_Price { get; set; }
        public decimal CGST { get; set; }
        public decimal SGST { get; set; }
        [Display(Name = "Administrator Token number")]
        public string Administrator_Token_number { get; set; }
        [Display(Name = "Administrator name")]
        public string Administrator_name { get; set; }
        [Display(Name = "Approve date")]
        public System.DateTime Approve_date { get; set; }
        public bool Approve { get; set; }
        [Display(Name = "Selling price")]
        public decimal Selling_Price { get; set; }
        public int StockIn { get; set; }
        public decimal Up_Selling_Price { get; set; }
        public decimal Up_CGST { get; set; }
        public decimal Up_SGST { get; set; }
        [Display(Name = "Delivery contact number")]
        public long Delivery_contact_number { get; set; }
        [Display(Name = "Delivery address")]
        public string Delivery_address { get; set; }
        [Display(Name = "Item Id")]
        public string Item_tyre_Id { get; set; }
        [Display(Name = "Invoice number")]
        public string Purchase_number { get; set; }
        [Display(Name ="Invoice date")]
        public System.DateTime PurchaseDate { get; set; }
        [Display(Name = "Tyre make")]
        public string Tyre_make { get; set; }
        [Display(Name = "Tyre type")]
        public string Tyre_type { get; set; }
        [Display(Name = "Tyre feel")]
        public string Tyre_feel { get; set; }
        public virtual Product Product { get; set; }
    }
}
