//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Purchase_detail
    {
        public int Purchase_details_number { get; set; }
        public string Purchase_Token_number { get; set; }
        public string Purcahse_number { get; set; }
        public System.DateTime Date { get; set; }
        public string Product_Token { get; set; }
        public string Product_name { get; set; }
        public int Pieces { get; set; }
        public decimal Quantity { get; set; }
        public decimal Amount { get; set; }
        public decimal Taxable_amount { get; set; }
        public string Tax_Token { get; set; }
        public decimal Tax { get; set; }
        public decimal Discount_percent { get; set; }
        public decimal Discount { get; set; }
        public decimal Sub_Total { get; set; }

        public virtual Purchase_Master Purchase_Master { get; set; }
    }
}
