//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Invoice
    {
        public string Token_number { get; set; }
        public string Purchase_invoice_number { get; set; }
        public System.DateTime Date { get; set; }
        public string Stock_entry_token { get; set; }
    }
}
