//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Tax_Group
    {
        public string Tax_Token { get; set; }
        public string Tax_Name { get; set; }
        public double Tax_Rate { get; set; }
        public string GL_CODE { get; set; }
        public bool IsActive { get; set; }
        public string Marchent_Token_number { get; set; }
    }
}


