//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Temp_placedorder
    {
        public string Token_number { get; set; }
        public string Item_token { get; set; }
        public string Customer_token { get; set; }
        public bool IsUser { get; set; }
        public System.DateTime Order_Date { get; set; }
        public Nullable<int> Pieces { get; set; }
        public decimal Primaryprice { get; set; }
        public string Productname { get; set; }
        public decimal price { get; set; }
    }
}


