//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tyre_size
    {
        [Display(Name = "Token")]
        public string Token_number { get; set; }
        [Display(Name = "Tyre size")]
        public string Tyre_size1 { get; set; }
        [Display(Name = "With/without tube")]
        public bool With_tube { get; set; }
    }
}

