//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vehicle
    {
        [Display(Name = "Token number")]
        public string Token_number { get; set; }
        [Display(Name = "Vehicletype")]
        public string Vehicle_type { get; set; }
        [Display(Name = "Vehicle make")]
        public string Vehicle_make { get; set; }
    }
}


